name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install packages
      run: sudo apt-get install check clang clang-tools lcov libsafec-dev
    - name: make
      run: make
